import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-fit min-h-screen grid grid-rows-[72px_1fr] space-y-2 p-2`}>
        <AuthProvider>
          <Header />
          <div className="bg-blue-100 rounded-lg shadow-lg">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
